name: Update MySchool Music Calendar

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    environment: prod
    runs-on: ubuntu-latest
    env:
      MYSCHOOL_USERNAME: ${{ secrets.MYSCHOOL_USERNAME }}
      MYSCHOOL_PASSWORD: ${{ secrets.MYSCHOOL_PASSWORD }}
    defaults:
      run:
        working-directory: gen
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps + browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Generate ICS
        run: python generate.py

      - name: Commit & push
        run: |
          git config user.name "calendar-bot"
          git config user.email "calendar-bot@users.noreply.github.com"
          git add calendars/*.ics
          git commit -m "auto: update calendar" || echo "No changes"
          git pull --rebase
          git push
