name: Update MySchool Music Calendar

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*


jobs:
  test_update:
    name: Update
    runs-on: ubuntu-latest
    env:
      MYSCHOOL_USERNAME: ${{ secrets.MYSCHOOL_USERNAME }}
      MYSCHOOL_PASSWORD: ${{ secrets.MYSCHOOL_PASSWORD }}
    defaults:
      run:
        working-directory: gen/
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install dependencies & browsers
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps chromium
        #    - name: Common Tests
        #      run: pytest
    - name: Generate ICS
      run: python generate.py
      #
      #    - name: Commit & push
      #      run: |
      #        git config user.name "calendar-bot"
      #        git config user.email "calendar-bot@users.noreply.github.com"
      #        git add calendars/*.ics
      #        git commit -m "auto: update calendar" || echo "No changes"
      #        git push
