name: Update MySchool Music Calendar

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      MYSCHOOL_USERNAME: ${{ secrets.MYSCHOOL_USERNAME }}
      MYSCHOOL_PASSWORD: ${{ secrets.MYSCHOOL_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install Playwright browser
        run: playwright install --with-deps chromium
        
#      - name: Generate ICS
#         run: python generate.py

      - name: Debug login
        run: python debug_login.py
      
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-login
          path: debug/

      - name: Commit & push
        run: |
          git config user.name "calendar-bot"
          git config user.email "calendar-bot@users.noreply.github.com"
          git add calendars/*.ics
          git commit -m "auto: update calendar" || echo "No changes"
          git push
